---
dist: xenial

services:
  - docker

language: minimal

jobs:
  include:
    - stage: Lint
      before_script:
      # Prepara i container per il lancio
        - docker pull php:latest
      script:
      # Usa il linter di PHP
        - docker run --rm -it -v $(pwd)/:/saw --entrypoint find php:latest /saw -name '*.php' -type f -exec php -l -f {} \;
    - stage: Lint
      before_script:
      # Prepara i container per il lancio
        - docker pull node:latest
      # Lancia in background il container
        - docker run --rm --detach --name node -v $(pwd)/.eslintrc.json:/eslintrc.json -v $(pwd)/:/saw node:latest /bin/sh -c 'while true; do sleep 3600; done'
      # Installa i tool nel container
        - docker exec node npm install -g eslint
      script:
      # Analizza staticamente il JS
        - docker exec node eslint --config /eslintrc.json /saw/**/*.js || true
      after_script:
      # Spegni il container
        - docker rm --force node
    - stage: Upload
      addons:
        apt:
          packages:
            - lftp
      script:
      # Prepara la configurazione
        - sed -ie "s/databaseName = \"saw\"/databaseName = \"${USER}\"/" lib/config.php
        - sed -ie "s/databaseUser = \"saw\"/databaseUser = \"${USER}\"/" lib/config.php
        - sed -ie "s/databasePassword = \"saw\"/databasePassword = \"${PASS}\"/" lib/config.php
        - sed -ie "s/isDevelopment = TRUE/isDevelopment = FALSE/" lib/config.php
      # Carica sul server
        - lftp -e "set sftp:auto-confirm yes; mirror --continue --delete --recursion=always --reverse --verbose docs docs; exit" -u ${USER},${PASS} sftp://${SERVER}
        - lftp -e "set sftp:auto-confirm yes; mirror --continue --delete --recursion=always --reverse --verbose lib lib; exit" -u ${USER},${PASS} sftp://${SERVER}
        - lftp -e "set sftp:auto-confirm yes; mirror --continue --delete --recursion=always --reverse --verbose html public_html; exit" -u ${USER},${PASS} sftp://${SERVER}
    - stage: Validate
      addons:
        apt:
          packages:
            - wget
      before_script:
      # Scarica ogni singola pagina
        - wget --recursive --level=4096 --convert-links --page-requisites --no-directories --directory-prefix=downloaded https://webdev.dibris.unige.it/~S4336488
      script:
      # Valida le pagine scaricate
        - docker run --rm -it -v $(pwd)/downloaded:/saw validator/validator java -jar /vnu.jar --skip-non-html --also-check-css --format text /saw

notifications:
  email:
    - alessandro.orlich@live.it
    - gabibbo97@gmail.com
    - roberta.tassara.97@gmail.com
