CREATE TABLE IF NOT EXISTS articolo (
    id SERIAL PRIMARY KEY,
    titolo VARCHAR(100) NOT NULL,
    sottotitolo VARCHAR(200) NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    corpo MEDIUMTEXT NOT NULL,
    autore VARCHAR(20) NOT NULL,
    FOREIGN KEY (autore) REFERENCES utente (username) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE FULLTEXT INDEX IF NOT EXISTS testo_articoli ON articolo(corpo);
